### ISSUE TITLE
Determine a quantifiable metric

### ISSUE THREAD

**Issue by SAMofNAV** [fernandodlcruz/HotelReservation#6]
We are not familiar with ways in which we can quantify our work. We need to perform some brainstorming to find an accurate form of progress measurement.

**Comment by fernandodlcruz** [comment]
One of the KPIs that I think is good to measure is the velocity. Here is a quick explanation from Atlassian:

"Velocity is the average amount of work a scrum team completes during a sprint, measured in either story points or hours, and is very useful for forecasting. The product owner can use velocity to predict how quickly a team can work through the backlog, because the report tracks the forecasted and completed work over several iterations–the more iterations, the more accurate the forecast.

Let's say the product owner wants to complete 500 story points in the backlog. We know that the development team generally completes 50 story points per iteration. The product owner can reasonably assume the team will need 10 iterations (give or take) to complete the required work.

It's important to monitor how velocity evolves over time. New teams can expect to see an increase in velocity as the team optimizes relationships and the work process. Existing teams can track their velocity to ensure consistent performance over time, and can confirm that a particular process change made improvements or not. A decrease in average velocity is usually a sign that some part of the team's development process has become inefficient and should be brought up at the next retrospective.


ANTI-PATTERNS TO WATCH FOR
When velocity is erratic over a long period of time, always revisit the team's estimation practices. During the team's retrospective, ask the following questions:

Are there unforeseen development challenges we didn't account for when estimating this work? How can we better break down work to uncover some of these challenges?
Is there outside business pressure pushing the team beyond its limits? Is adherance to development best practices suffering as a result?
As a team, are we overzealous in forecasting for the sprint? 
Each team’s velocity is unique. If team A has a velocity of 50 and team B has a velocity of 75, it doesn't mean that team B has higher throughput. Since each team's estimation culture is unique, their velocity will be as well. Resist the temptation to compare velocity across teams. Measure the level of effort and output of work based on each team's unique interpretation of story points."

Reference: https://www.atlassian.com/agile/project-management/metrics
